### ISSUE TITLE
[error] (*:update) sbt.ResolveException: unresolved dependency: com.android.support#support-v4;21.0.3: not found

### ISSUE THREAD

**Issue by scheung38** [47deg/macroid-starter#8]
Seems like com.android.support-v4;21.0.3 not found, but the build.sbt has

platformTarget in Android := "android-21"
scalaVersion := "2.11.6"

but I have installed latest 

Android API 23
Android SDK Tools 24.4.1
Android SDK Platform-tools 23.1
Android SDK Build-tools 23.0.2

so what do I need to do to point at 
platformTarget in Android := "android-2x" ???
scalaVersion := "2.xx.x" ??? <- this corresponds to 

SDK Tools, Platform-tools or Build-tools number?

EDIT:
Change this to 
com.android.support" % "support-v4" % "21.0.3") <- 23.1.1? 

which is now
com.android.support" % "support-v4" % "23.1.1") 

But still says cannot find

com.android.support#support-v4;23.1.1: not found
but android manager already installed under Extras

Android Support Library 23.1.1 as Installed

I installed via

$ brew install android-sdk

so not sure whether this is changing the Cellar link of sdk directories

Then when trying to open in Intellij Ultimate by selecting Open, selected build.sbt...won't even open but hangs forever.

**Comment by Araxor** [comment]
I solved the same issue by installing the package **Local Maven repository for Support Libraries** in Android SDK manager.
